---
- name: set overpass_database_dir
  set_fact:
    overpass_database_dir: "{{ ssd_dir|default(work_dir) }}/database"

- name: create overpass_database_dir and webroot_dir
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ overpass_user }}"
    group: "{{ overpass_user }}"
  with_items:
    - "{{ overpass_database_dir }}"
    - "{{ webroot_dir }}"

- import_tasks: compile.yml
- import_tasks: set_up_database.yml
- import_tasks: services.yml
- import_tasks: web.yml

- block:
  - name: test if munin-node is installed
    stat:
      path: /usr/sbin/munin-node
    register: munin
  - import_tasks: munin.yml
    when: munin.stat.exists
  tags: munin

- block:
  - name: test if telegraf is installed
    stat:
      path: /usr/bin/telegraf
    register: telegraf
  - import_tasks: telegraf.yml
    when: telegraf.stat.exists
  tags: telegraf
