---
- name: restart munin-node
  service:
    name: munin-node
    state: restarted

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: restart telegraf
  service:
    name: telegraf
    state: restarted
