---
- name: install influxdb server
  apt:
    pkg: influxdb
    update_cache: yes

- name: enable authentication
  ini_file:
    path: /etc/influxdb/influxdb.conf
    section: http
    option: "  auth-enabled"
    value: "true"
  register: enable_auth
  notify: reload influxdb

- name: restart influxdb
  block:
    - service:
        name: influxdb
        state: restarted
    - wait_for:
        port: 8086
        delay: 3
  when: enable_auth.changed

- name: add admin users
  influxdb_user:
    login_username: "ansible"
    login_password: "{{ influxdb.admins.ansible.password }}"
    user_name: "{{ item.key }}"
    user_password: "{{ item.value.password }}"
    admin: yes
  with_dict: "{{ influxdb.admins }}"

- name: add normal users
  influxdb_user:
    login_username: "ansible"
    login_password: "{{ influxdb.admins.ansible.password }}"
    user_name: "{{ item.key }}"
    user_password: "{{ item.value.password }}"
  with_dict: "{{ influxdb.users }}"

- name: create databases
  influxdb_database:
    login_username: "ansible"
    login_password: "{{ influxdb.admins.ansible.password }}"
    database_name: "{{ item }}"
  with_items: "{{ influxdb.databases }}"

- name: grant read access to read only users
  command: /usr/bin/influx -username ansible -password "{{ influxdb.admins.ansible.password }}" -execute "GRANT {{ item.value.grant }} ON {{ item.value.database }} TO {{ item.key }}"
  with_dict: "{{ influxdb.users }}"
