---
- name: install base packages
  apt:
    pkg:
      - git
      - etckeeper
      - htop
      - nano
      - vim-nox
      - tmux
      - screen
      - apt-transport-https
      - ssmtp
      - unattended-upgrades
      - fish
    update_cache: yes

- name: remove useless packages
  apt:
    pkg:
      - exim4
      - exim4-base
      - exim4-config
      - exim4-daemon-light
    state: absent
    purge: yes

# FIXME:
#- name: configure ssmtp

- name: create APT auto-upgrades configuration
  copy:
    src: files/apt.conf.d/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
  notify: restart unattended-upgrades

- name: create project and work dir
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    force: no
  with_items:
    - "{{ base_project_dir }}"
    - "{{ base_work_dir }}"

- import_tasks: service-user.yml
  when: "service_user is defined"

- import_tasks: systemd.yml
  when: ansible_service_mgr == 'systemd'
