---
- name: create service user
  user:
    name: "{{ service_user }}"
    home: "{{ project_dir }}"
    system: yes
    generate_ssh_key: yes

- name: create work_dir
  file:
    path: "{{ work_dir }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"

- name: create ssd_dir
  file:
    path: "{{ ssd_dir }}"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
  when: "ssd_dir is defined"
