---
- name: install postgresql package
  apt:
    pkg: "postgresql-{{ postgresql_version }},python-psycopg2"
    update_cache: yes

- name: create database
  postgresql_db:
    name: "{{ postgresql_user }}"
  become_user: postgres

- name: grant access to database
  postgresql_user:
    db: "{{ postgresql_user }}"
    name: "{{ postgresql_user }}"
    password: "{{ postgresql_user }}"
    role_attr_flags: CREATEDB
  become_user: postgres

- block:
  - name: test if telegraf is installed
    stat:
      path: /usr/bin/telegraf
    register: telegraf
  - import_tasks: telegraf.yml
    when: telegraf.stat.exists
  tags: telegraf
