---
- name: create users
  user:
    name: "{{ item.key }}"
    shell: "{{ item.value.shell }}"
    uid: "{{ item.value.uid }}"
    groups: adm {% if item.value.superadmin %}, sudo{% endif %}
  with_dict: "{{ users }}"

- name: add ssh public key
  authorized_key:
    user: "{{ item.key }}"
    key: "{{ item.value.pubkey }}"
  with_dict: "{{ users }}"

- name: add local admin user
  user:
    name: "{{ item.name }}"
    groups: sudo
    append: yes
  with_items: "{{ admins|default([]) }}"
