---
- include_tasks: debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- include_tasks: centos.yml
  when: ansible_distribution == "Centos"

- name: add telegraf.conf
  template:
    src: templates/telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: reload telegraf

- name: configure telegraf
  template:
    src: "templates/{{ item }}.conf.j2"
    dest: "/etc/telegraf/telegraf.d/{{ item }}.conf"
  with_items:
    - outputs.influxdb
    - inputs.net
  notify: reload telegraf
