---
- name: set service_user and work_dir
  set_fact:
    project_dir: "{{ base_project_dir }}/{{ service_user }}"
    work_dir: "{{ base_project_dir }}/{{ service_user }}"
  when: "service_user is defined"

- name: set ssd_dir
  set_fact:
    ssd_dir: "{{ base_ssd_dir }}/{{ service_user }}"
  when: "base_ssd_dir is defined"

- name: set webroot_dir
  set_fact:
    webroot_dir: "{{ work_dir }}/www"
  when: "work_dir is defined"
