---
- name: add grafana apt key
  apt_key:
    url: https://packagecloud.io/gpg.key
    state: present

- name: add grafana repository
  apt_repository:
    repo: deb https://packagecloud.io/grafana/stable/debian/ stretch main

- name: install grafana
  apt:
    pkg: grafana
    update_cache: yes
  notify: restart grafana

- name: enable grafana service
  systemd:
    name: grafana-server
    enabled: yes
    daemon_reload: yes

- name: install libcap2-bin
  apt:
    pkg: libcap2-bin
    state: present

- name: add cap_net_bind_service capability to grafana
  capabilities:
    path: /usr/sbin/grafana-server
    capability: cap_net_bind_service+ep
    state: present

- name: copy config file
  copy:
    src: files/grafana.ini
    dest: /etc/grafana/grafana.ini
    mode: 0640
    group: grafana
  notify: restart grafana

- name: add influxdb datasources
  template:
    src: templates/datasources.yml.j2
    dest: /etc/grafana/provisioning/datasources/influxdb.yml
  notify: restart grafana
